### ISSUE TITLE
No longer works since upgrade to latest 'canvas' lib

### ISSUE THREAD

**Issue by uncopied** [uncopied/tallystick#1]
Hi Alex, cc Taco,

I tried to upgrade chirograph with latest 'canvas' lib by Taco de Wolff (https://github.com/tdewolff) in order to solve the fonts issue (https://github.com/tdewolff/canvas/issues/75) but now something is broken. 

The only thing I changed in the code was to comment out,
// fontFamily.Use(canvas.CommonLigatures)

Best,
Elian

panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/tdewolff/canvas/font.(*SFNT).Subset(0xc00013c420, 0xc000b1a600, 0x41, 0x80, 0xc000d1af00, 0xc0000201c0, 0x8, 0x40, 0x8, 0x0)
        /home/elian/git/chirograph/vendor/github.com/tdewolff/canvas/font/sfnt_subset.go:30 +0x713a
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).writeFont(0xc000d20000, 0x4, 0xc0001364e0, 0x0)
        /home/elian/git/chirograph/vendor/github.com/tdewolff/canvas/renderers/pdf/writer.go:245 +0x75
github.com/tdewolff/canvas/renderers/pdf.(*pdfWriter).Close(0xc000d20000, 0x6d66c8, 0xc000178bc0)
        /home/elian/git/chirograph/vendor/github.com/tdewolff/canvas/renderers/pdf/writer.go:441 +0x1e5
github.com/tdewolff/canvas/renderers/pdf.(*PDF).Close(...)
        /home/elian/git/chirograph/vendor/github.com/tdewolff/canvas/renderers/pdf/pdf.go:67
github.com/tdewolff/canvas/renderers/pdf.Writer(0x6d3800, 0xc000134160, 0xc000178160, 0x1b6, 0xc000134160)
        /home/elian/git/chirograph/vendor/github.com/tdewolff/canvas/renderers/pdf/pdf.go:17 +0x92
github.com/tdewolff/canvas.(*Canvas).WriteFile(0xc000178160, 0xc00085b044, 0x7, 0x699308, 0x4, 0xc00085b044)
        /home/elian/git/chirograph/vendor/github.com/tdewolff/canvas/canvas.go:546 +0x92
main.main()
        /home/elian/git/chirograph/chirograph/main.go:59 +0x333

Process finished with the exit code 2

**Comment by tdewolff** [comment]
Thanks for the bug report! The problem was in the `loca` table which is in short format for the Montserrat font you're using. This is fixed in https://github.com/tdewolff/canvas/commit/cf0a904ed34e54d4d8fd44858be8e69a5080876f, please let me know if that works!
